### ISSUE TITLE
Undefined symbol: _ZNK2at6Tensor6deviceEv

### ISSUE THREAD

**Issue by D1st3f** [xuxw98/ESAM#13]
I installed all like in readme, trying to run scene but take an error.

CUDA_VISIBLE_DEVICES=0 python tools/test.py configs/ESAM_CA/ESAM_online_scenenn_CA_test.py work_dirs/ESAM_online_scannet200_CA/epoch_128.pth --work-dir work_dirs/ESAM_online_scenenn_CA_test/
Traceback (most recent call last):
  File "tools/test.py", line 149, in <module>
    main()
  File "tools/test.py", line 105, in main
    cfg = Config.fromfile(args.config)
  File "/home/dmytro_pyrih/miniconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/config/config.py", line 182, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/dmytro_pyrih/miniconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/dmytro_pyrih/miniconda3/envs/ESAM/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/dmytro_pyrih/ESAM/oneformer3d/oneformer3d.py", line 4, in <module>
    from torch_scatter import scatter_mean
  File "/home/dmytro_pyrih/miniconda3/envs/ESAM/lib/python3.8/site-packages/torch_scatter/__init__.py", line 16, in <module>
    torch.ops.load_library(spec.origin)
  File "/home/dmytro_pyrih/miniconda3/envs/ESAM/lib/python3.8/site-packages/torch/_ops.py", line 104, in load_library
    ctypes.CDLL(path)
  File "/home/dmytro_pyrih/miniconda3/envs/ESAM/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/dmytro_pyrih/miniconda3/envs/ESAM/lib/python3.8/site-packages/torch_scatter/_scatter_cuda.so: undefined symbol: _ZNK2at6Tensor6deviceEv

**Comment by D1st3f** [comment]
1.9.0+cu102
torch_sparse-0.6.18

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243

**Comment by xuxw98** [comment]
Hi,
Thanks for your interest! You can try to add `PYTHONPATH="$(dirname $0)/..":$PYTHONPATH` before the script.

`PYTHONPATH="$(dirname $0)/..":$PYTHONPATH CUDA_VISIBLE_DEVICES=0 python xxx`

**Comment by xuxw98** [comment]
The undefined symbol error may due to an incomplete installation of torch_scatter.

You can search relevant solutions in the issues of that repo.

**Comment by D1st3f** [comment]
![image](https://github.com/user-attachments/assets/171d461e-643e-4cc2-a47c-8e192d93b523)

**Comment by D1st3f** [comment]
It's definitly something with torch_scatte

**Comment by xuxw98** [comment]
We recommend this [soluiton](https://github.com/rusty1s/pytorch_scatter/issues/370). Hope it works.

**Comment by D1st3f** [comment]
I fixed. Waiting untill dataset will download
