### ISSUE TITLE
When I try evaluate ESAM on 3RScan-MV, I meet a problem: "ModuleNotFoundError: No module named 'oneformer3d'"

### ISSUE THREAD

**Issue by dctwan15** [xuxw98/ESAM#15]
Traceback (most recent call last):
  File "/home/duan/miniconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/utils/misc.py", line 77, in import_modules_from_strings
    imported_tmp = import_module(imp)
  File "/home/duan/miniconda3/envs/ESAM/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'oneformer3d'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/duan/miniconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/config/config.py", line 466, in fromfile
    import_modules_from_strings(**cfg_dict['custom_imports'])
  File "/home/duan/miniconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/utils/misc.py", line 84, in import_modules_from_strings
    raise ImportError(f'Failed to import {imp}')
ImportError: Failed to import oneformer3d

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "tools/test.py", line 150, in <module>
    main()
  File "tools/test.py", line 103, in main
    cfg = Config.fromfile(args.config)
  File "/home/duan/miniconda3/envs/ESAM/lib/python3.8/site-packages/mmengine/config/config.py", line 478, in fromfile
    raise ImportError(err_msg) from e
ImportError: Failed to import custom modules from {'imports': ['oneformer3d']}, the current sys.path is: 
    /mnt/sda/duan/ESAM-main/tools
    /home/duan/miniconda3/envs/ESAM/lib/python38.zip
    /home/duan/miniconda3/envs/ESAM/lib/python3.8
    /home/duan/miniconda3/envs/ESAM/lib/python3.8/lib-dynload
    /home/duan/miniconda3/envs/ESAM/lib/python3.8/site-packages
    /home/duan/miniconda3/envs/ESAM/lib/python3.8/site-packages/MinkowskiEngine-0.5.4-py3.8-linux-x86_64.egg
    /home/duan/miniconda3/envs/ESAM/lib/python3.8/site-packages/pointops-1.0-py3.8-linux-x86_64.egg
You should set `PYTHONPATH` to make `sys.path` include the directory which contains your custom module

**Comment by dctwan15** [comment]
I tried clone oneformer3d code to work_dirs/tmp and append work_dirs/tmp to sys.path
